version: "3.2"

volumes:
  db_scripts:

services:
  db:
    container_name: test_db
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./db_scripts
        target: /tmp/db_scripts
      - db_scripts:/var/lib/mysql
  # need to find a way to connect test to db
  # test:
  #   container_name: test_scripts
  #   depends_on:
  #     - db
  #   build: .
  #   volumes:
  #     - type: bind
  #       source: ./tests
  #       target: /app/tests
