version: "3.2"

volumes:
  db_data:

services:
  db:
    container_name: test_db
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./db_data
        target: /tmp/db_data
      - db_data:/var/lib/mysql
